import {
  BotIcon,
  BrainCircuitIcon,
  CircleGaugeIcon,
  DatabaseIcon,
  MonitorIcon,
  WrenchIcon,
} from "lucide-react";

import type { SettingDefinition, SettingSection } from "./configuration-types";

/* Shared user-scoped sections are kept separate from navigation assembly. */
export const configurationUserSections: SettingSection[] = [
  {
    id: "models",
    label: "模型",
    description: "选择默认模型、调整生成行为并管理自定义模型。",
    icon: BotIcon,
    settings: [
      {
        path: ["models", "default"],
        label: "默认模型",
        description: "新会话默认使用的模型或自定义模型名称。",
        kind: "string",
      },
      {
        path: ["models", "web_search"],
        label: "联网搜索模型",
        description: "需要联网检索时使用的模型。",
        kind: "string",
        placeholder: "例如 grok-4.20-multi-agent",
      },
      {
        path: ["models", "temperature"],
        label: "温度",
        description: "控制回复随机性；留空时由模型决定。",
        kind: "number",
        min: 0,
        max: 2,
        step: 0.1,
      },
      {
        path: ["models", "top_p"],
        label: "Top P",
        description: "限制候选词概率范围；留空时由模型决定。",
        kind: "number",
        min: 0,
        max: 1,
        step: 0.05,
      },
      {
        path: ["models", "max_completion_tokens"],
        label: "最大输出 Token",
        description: "单次回复可生成的最大 Token 数。",
        kind: "number",
        min: 1,
        step: 1,
      },
      {
        path: ["models", "max_retries"],
        label: "最大重试次数",
        description: "模型请求失败后的自动重试上限。",
        kind: "number",
        defaultValue: 8,
        min: 0,
        step: 1,
      },
      {
        path: ["models", "inference_idle_timeout_secs"],
        label: "推理空闲超时",
        description: "流式响应无新内容后等待的秒数。",
        kind: "number",
        defaultValue: 600,
        min: 1,
        step: 1,
      },
      {
        path: ["models", "stream_tool_calls"],
        label: "流式工具调用",
        description: "允许在模型尚未结束输出时开始解析工具调用。",
        kind: "boolean",
        defaultValue: true,
      },
      {
        path: ["models", "extra_headers"],
        label: "全局请求头",
        description: "每行填写“名称=值”，应用到所有模型请求。",
        kind: "key-value",
      },
    ],
  },
  {
    id: "melody-appearance",
    label: "界面",
    description: "终端界面、滚动和内容展示方式。",
    icon: MonitorIcon,
    settings: [
      {
        path: ["ui", "simple_mode"],
        label: "简洁模式",
        description: "减少界面装饰，保持紧凑展示。",
        kind: "boolean",
        defaultValue: true,
      },
      {
        path: ["ui", "vim_mode"],
        label: "Vim 模式",
        description: "在输入区启用 Vim 风格操作。",
        kind: "boolean",
        defaultValue: false,
      },
      {
        path: ["ui", "show_thinking_blocks"],
        label: "显示思考过程",
        description: "在会话中展示模型提供的思考块。",
        kind: "boolean",
        defaultValue: true,
      },
      {
        path: ["ui", "default_selected_permission"],
        label: "默认权限选项",
        description: "权限确认窗口默认选中的操作。",
        kind: "select",
        defaultValue: "always_allow_all_sessions",
        options: [
          { value: "allow_once", label: "仅允许一次" },
          { value: "always_allow_session", label: "本会话始终允许" },
          { value: "always_allow_all_sessions", label: "所有会话始终允许" },
          { value: "deny_once", label: "仅拒绝一次" },
        ],
      },
      {
        path: ["ui", "remember_tool_approvals"],
        label: "记住工具授权",
        description: "在后续会话中继续应用已确认的工具授权。",
        kind: "boolean",
        defaultValue: false,
      },
      {
        path: ["ui", "group_tool_verbs"],
        label: "合并工具活动",
        description: "将连续的读取、搜索或编辑操作折叠成活动组。",
        kind: "boolean",
        defaultValue: true,
      },
      {
        path: ["ui", "collapsed_edit_blocks"],
        label: "默认折叠编辑内容",
        description: "文件编辑完成后默认收起差异详情。",
        kind: "boolean",
        defaultValue: false,
      },
      {
        path: ["ui", "page_flip_on_send"],
        label: "发送后翻页",
        description: "发送消息时自动移动到最新内容。",
        kind: "boolean",
        defaultValue: true,
      },
      {
        path: ["ui", "scroll_mode"],
        label: "滚动模式",
        description: "按输入设备优化滚动手感。",
        kind: "select",
        defaultValue: "auto",
        options: [
          { value: "auto", label: "自动" },
          { value: "wheel", label: "鼠标滚轮" },
          { value: "trackpad", label: "触控板" },
        ],
      },
      {
        path: ["ui", "scroll_speed"],
        label: "滚动速度",
        description: "滚动响应速度，范围 1–100。",
        kind: "number",
        defaultValue: 50,
        min: 1,
        max: 100,
        step: 1,
      },
      {
        path: ["ui", "scroll_lines"],
        label: "每次滚动行数",
        description: "鼠标滚轮每步移动的行数。",
        kind: "number",
        min: 1,
        max: 10,
        step: 1,
      },
      {
        path: ["ui", "invert_scroll"],
        label: "反转滚动方向",
        description: "反转鼠标或触控板的滚动方向。",
        kind: "boolean",
        defaultValue: false,
      },
      {
        path: ["ui", "max_thoughts_width"],
        label: "思考内容最大宽度",
        description: "思考块每行允许显示的最大字符数。",
        kind: "number",
        defaultValue: 120,
        min: 40,
        step: 1,
      },
    ],
  },
  {
    id: "features",
    label: "功能",
    description: "可选能力、隐私和索引行为。",
    icon: CircleGaugeIcon,
    settings: [
      {
        path: ["features", "lsp_tools"],
        label: "LSP 工具",
        description: "允许代理使用语言服务器能力。",
        kind: "boolean",
        defaultValue: false,
      },
      {
        path: ["features", "codebase_indexing"],
        label: "代码库索引",
        description: "为项目建立索引以改进代码检索。",
        kind: "boolean",
        defaultValue: true,
      },
      {
        path: ["features", "two_pass_compaction"],
        label: "两阶段上下文压缩",
        description: "使用额外阶段改善长会话压缩质量。",
        kind: "boolean",
        defaultValue: false,
      },
      {
        path: ["features", "remote_fetch"],
        label: "远程内容获取",
        description: "允许工具读取远程网页内容。",
        kind: "boolean",
        defaultValue: true,
      },
      {
        path: ["tools", "respect_gitignore"],
        label: "遵循 .gitignore",
        description: "文件搜索和扫描时排除 Git 忽略项。",
        kind: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    id: "tools",
    label: "工具",
    description: "命令执行、提问和网页获取限制。",
    icon: WrenchIcon,
    settings: [
      {
        path: ["toolset", "bash", "timeout_secs"],
        label: "命令超时",
        description: "单个终端命令允许运行的秒数。",
        kind: "number",
        defaultValue: 120,
        min: 1,
      },
      {
        path: ["toolset", "bash", "output_byte_limit"],
        label: "命令输出上限",
        description: "单次命令保留的最大输出字节数。",
        kind: "number",
        defaultValue: 20000,
        min: 1000,
        step: 1000,
      },
      {
        path: ["toolset", "ask_user_question", "timeout_enabled"],
        label: "提问超时",
        description: "等待用户回答时启用超时限制。",
        kind: "boolean",
        defaultValue: true,
      },
      {
        path: ["toolset", "ask_user_question", "timeout_secs"],
        label: "提问等待时间",
        description: "等待用户回答的最大秒数。",
        kind: "number",
        defaultValue: 1800,
        min: 1,
      },
      {
        path: ["toolset", "web_fetch", "proxy_endpoint"],
        label: "网页代理地址",
        description: "通过指定代理访问网页；留空表示直连。",
        kind: "string",
        placeholder: "https://proxy.example.com",
      },
      {
        path: ["toolset", "web_fetch", "allowed_domains"],
        label: "网页域名白名单",
        description: "每行一个允许访问的域名；留空表示不限制。",
        kind: "string-list",
        placeholder: "docs.rs\nexample.com",
      },
      {
        path: ["toolset", "web_fetch", "allow_local"],
        label: "允许访问本地地址",
        description: "允许网页工具访问 localhost 和局域网地址。",
        kind: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    id: "session",
    label: "会话与记忆",
    description: "长会话压缩、环境加载和持久记忆。",
    icon: BrainCircuitIcon,
    settings: [
      {
        path: ["session", "auto_compact_threshold_percent"],
        label: "自动压缩阈值",
        description: "上下文占用达到此百分比时自动压缩。",
        kind: "number",
        defaultValue: 85,
        min: 1,
        max: 100,
      },
      {
        path: ["session", "load_envrc"],
        label: "加载 .envrc",
        description: "进入项目后加载 direnv 环境。",
        kind: "boolean",
        defaultValue: true,
      },
      {
        path: ["memory", "enabled"],
        label: "持久记忆",
        description: "允许 Melody 保存并检索跨会话记忆。",
        kind: "boolean",
        defaultValue: false,
      },
      {
        path: ["memory", "session", "save_on_end"],
        label: "结束时保存记忆",
        description: "会话结束时自动提取并保存有用信息。",
        kind: "boolean",
        defaultValue: false,
      },
      {
        path: ["memory", "watcher", "enabled"],
        label: "记忆文件监听",
        description: "监控记忆文件变化并自动更新索引。",
        kind: "boolean",
        defaultValue: false,
      },
      {
        path: ["memory", "search", "max_results"],
        label: "记忆检索数量",
        description: "单次检索最多返回的记忆条数。",
        kind: "number",
        min: 1,
      },
      {
        path: ["memory", "search", "min_score"],
        label: "记忆最低相关度",
        description: "过滤低相关度记忆，范围 0–1。",
        kind: "number",
        min: 0,
        max: 1,
        step: 0.05,
      },
      {
        path: ["memory", "initial_injection", "enabled"],
        label: "初始记忆注入",
        description: "开始会话时自动注入相关记忆。",
        kind: "boolean",
        defaultValue: false,
      },
      {
        path: ["memory", "initial_injection", "min_score"],
        label: "初始记忆最低相关度",
        description: "仅注入高于此相关度的记忆。",
        kind: "number",
        min: 0,
        max: 1,
        step: 0.05,
      },
      {
        path: ["memory", "embedding", "model"],
        label: "嵌入模型",
        description: "生成记忆向量所使用的模型。",
        kind: "string",
      },
      {
        path: ["memory", "embedding", "dimensions"],
        label: "嵌入维度",
        description: "嵌入模型输出向量的维度。",
        kind: "number",
        min: 1,
      },
    ],
  },
  {
    id: "agents",
    label: "代理",
    description: "子代理、工作流和技能发现。",
    icon: BotIcon,
    settings: [
      {
        path: ["subagents", "enabled"],
        label: "启用子代理",
        description: "允许主代理把独立工作委派给子代理。",
        kind: "boolean",
        defaultValue: true,
      },
      {
        path: ["subagents", "toggle", "explore"],
        label: "探索子代理",
        description: "允许使用专门的项目探索代理。",
        kind: "boolean",
        defaultValue: true,
      },
      {
        path: ["subagents", "toggle", "plan"],
        label: "规划子代理",
        description: "允许使用专门的规划代理。",
        kind: "boolean",
        defaultValue: true,
      },
      {
        path: ["subagents", "models", "explore"],
        label: "探索模型",
        description: "探索子代理使用的模型名称。",
        kind: "string",
      },
      {
        path: ["workflows", "enabled"],
        label: "启用工作流",
        description: "允许 Melody 发现并执行工作流。",
        kind: "boolean",
        defaultValue: true,
      },
      {
        path: ["skills", "paths"],
        label: "额外技能目录",
        description: "每行一个额外扫描的技能目录。",
        kind: "string-list",
      },
      {
        path: ["skills", "ignore"],
        label: "忽略的技能",
        description: "每行一个不参与扫描的技能名称或模式。",
        kind: "string-list",
      },
      {
        path: ["skills", "disabled"],
        label: "停用的技能",
        description: "每行一个明确停用的技能名称。",
        kind: "string-list",
      },
    ],
  },
  {
    id: "compatibility",
    label: "兼容性",
    description: "从其他编码工具导入约定和数据。",
    icon: DatabaseIcon,
    settings: [
      {
        path: ["compat", "agents", "skills"],
        label: "技能",
        description: "发现用户 ~/.agents 与当前工作目录 .agents 中的通用技能。",
        kind: "agents-skills-source",
        defaultValue: true,
      },
      ...(["claude", "cursor"] as const).flatMap((provider) =>
        [
          ["skills", "技能", "发现技能与旧式自定义命令。"],
          ["rules", "规则", "读取项目和用户级规则目录。"],
          ["agents", "代理指令", "读取命名的代理与项目指令文件。"],
          ["mcps", "MCP 服务器", "读取 MCP 服务器配置。"],
          ["hooks", "钩子", "读取生命周期钩子配置。"],
          ["sessions", "会话", "允许发现兼容的历史会话。"],
        ].map(([feature, label, description]): SettingDefinition => ({
          path: ["compat", provider, feature],
          label,
          description,
          kind: "boolean",
          defaultValue: true,
        })),
      ),
      {
        path: ["compat", "codex", "sessions"],
        label: "会话",
        description: "允许发现兼容的 Codex 历史会话。",
        kind: "boolean",
        defaultValue: true,
      },
    ],
  },
];
